-- MySQL Script generated by MySQL Workbench
-- mar 04 ene 2022 20:39:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS 3996491_proyecto DEFAULT CHARACTER SET utf8 ;
USE 3996491_proyecto;

-- -----------------------------------------------------
-- Table proyecto.CLIENTE
-- -----------------------------------------------------
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS CLIENTE ;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS CLIENTE (
  DNI VARCHAR(10) NOT NULL,
  Nombre VARCHAR(45) NOT NULL,
  Apellidos VARCHAR(45) NOT NULL,
  Email VARCHAR(45) NOT NULL,
  Telefono VARCHAR(12) NOT NULL,
  Direccion VARCHAR(45) NOT NULL,
  Codigo_postal VARCHAR(8) NOT NULL,
  Borrado TINYINT NULL,
  PRIMARY KEY (DNI),
  UNIQUE INDEX Email_UNIQUE (Email ASC),
  UNIQUE INDEX DNI_UNIQUE (DNI ASC),
  UNIQUE INDEX Telefono_UNIQUE (Telefono ASC));



-- -----------------------------------------------------
-- Table proyecto.PRODUCTOS
-- -----------------------------------------------------
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS PRODUCTOS ;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS PRODUCTOS (
  ID_Producto INT NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(45) NOT NULL,
  Familia VARCHAR(45) NOT NULL,
  Descripcion VARCHAR(45) NOT NULL,
  Dimensiones VARCHAR(45) NOT NULL,
  Peso DECIMAL(20,2) NOT NULL,
  PVP DECIMAL(20,2) NOT NULL,
  Image VARCHAR(45) NOT NULL,
  Stock INT NOT NULL,
  Borrado TINYINT NULL,
  PRIMARY KEY (ID_Producto),
  UNIQUE INDEX ID_Producto_UNIQUE (ID_Producto ASC));



-- -----------------------------------------------------
-- Table proyecto.COMPRA
-- -----------------------------------------------------
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS COMPRA ;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE IF NOT EXISTS COMPRA (
  ID_Compra INT UNSIGNED NOT NULL AUTO_INCREMENT,
  CLIENTE_DNI VARCHAR(10) NOT NULL,
  Borrado TINYINT NOT NULL,
  PRODUCTOS_ID_Producto INT NOT NULL,
  PRIMARY KEY (ID_Compra, CLIENTE_DNI),
  INDEX fk_COMPRA_CLIENTE_idx (CLIENTE_DNI ASC),
  INDEX fk_COMPRA_PRODUCTOS1_idx (PRODUCTOS_ID_Producto ASC),
  CONSTRAINT fk_COMPRA_CLIENTE
    FOREIGN KEY (CLIENTE_DNI)
    REFERENCES proyecto.CLIENTE (DNI)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_COMPRA_PRODUCTOS1
    FOREIGN KEY (PRODUCTOS_ID_Producto)
    REFERENCES proyecto.PRODUCTOS (ID_Producto)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- INSERTS CLIENTE
-- -----------------------------------------------------

INSERT INTO CLIENTE VALUES ("00000000A", "Juan", "López Gutierrez", "jlogu@gmail.com", "600600600", "Calle La Pardela", "38000", 0);

-- -----------------------------------------------------
-- INSERTS PRODUCTO
-- -----------------------------------------------------

INSERT INTO PRODUCTOS (Nombre, Familia, Descripcion, Dimensiones, Peso, PVP, Image, Stock, Borrado) VALUES ("Samsung QLED", "Televisor", "Una tele XD", "55 pulgadas", 10.5, 750.99, "url", 20, 0);
INSERT INTO PRODUCTOS (Nombre, Familia, Descripcion, Dimensiones, Peso, PVP, Image, Stock, Borrado) VALUES ("Intel Core i7-11700k", "Ordenadores", "Un procesador", "3 x 3 x 0.4", 0.8, 350.0, "url", 33, 0);

-- -----------------------------------------------------
-- INSERTS COMPRA
-- -----------------------------------------------------

INSERT INTO COMPRA (CLIENTE_DNI, Borrado, PRODUCTOS_ID_Producto) VALUES ("00000000A", 0 , 1);
INSERT INTO COMPRA (CLIENTE_DNI, Borrado, PRODUCTOS_ID_Producto) VALUES ("00000000A", 0 , 2);